name: Pylint

on: [push]

jobs:
  build:

    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v2
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
